import type { Metadata } from "next";
import { Raleway, Montserrat, Ubuntu_Mono, Geist } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeFavicon } from "@/components/theme-favicon";
import { AuthInitializer } from "@/components/providers/AuthInitializer";
import { GoogleProvider } from "@/components/providers/GoogleProvider";
import { FacebookProvider } from "@/components/providers/FacebookProvider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["400", "500", "600", "700", "800"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

const ubuntuMono = Ubuntu_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/cs_icon.svg",
    apple: "/cs_icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", geist.variable)}>
      <body
        className={`${raleway.variable} ${montserrat.variable} ${ubuntuMono.variable} font-raleway antialiased`}
        suppressHydrationWarning
      >
        <TooltipProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <ThemeFavicon />
            <GoogleProvider>
              <FacebookProvider>
                <AuthInitializer>
                  {children}
                  <Toaster position="bottom-right" />
                </AuthInitializer>
              </FacebookProvider>
            </GoogleProvider>
          </ThemeProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
